### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by ThisIsARealGithubUser**

### CODE REVIEW

**Review by FlrnDml — CHANGES_REQUESTED** [review]
no

**Comment by FlrnDml** [comment]
hey

**Review by FlrnDml — COMMENTED** [review]
hey

**Review by FlrnDml — CHANGES_REQUESTED** [review]
no

**Comment by ThisIsARealGithubUser** [comment]
> no

Okay

**Comment by FlrnDml** [comment]
Is this no comment? I dont get it, why is it not working as it should

**Review by ThisIsARealGithubUser — COMMENTED** [review]
is this a comment, i dont get it

**Pull request closed without merging**
